name: "CI/CD Laboratory work #5"

on:
  push:
    branches: [ "labwork_5_467934_2" ]
  pull_request:
    branches: [ "labwork_5_467934_2" ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os:
         [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: "📌 Checkout code"
        uses: actions/checkout@v4.2.2

      - name: "📌 Checkout testing branch"
        run: git fetch origin testing_465194 && git checkout testing_465194

      - name: "🐍 Install the latest version of Python"
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.13.0'

      - name: "⚙️ Install the necessary dependencies"
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt

      - name: "🙏 Run tests"
        run: |
          python -m unittest discover -p "test.py"