name: CI2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "new_features_409657" ]
  pull_request:
    branches: [ "new_features_409657" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    runs-on: ubuntu-latest, windows-latest

    
    steps:
     
      - uses: actions/checkout@v3

      
      - name: Run a multi-line script
        run: 
          python -m unittest tests/test_rectangle.py
  
