name: AUTO_TESTS

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        ops: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.ops}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: TEST_RUN
        run: python -m unittest tests.py
